import Head from 'next/head';
import dynamic from "next/dynamic";
import { useState } from 'react';
const TextEditor=dynamic(import("@/components/TextEditor"), { ssr: false });

export default function Home() {
  const [content, setContent] = useState('');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Text Editor 1</h1>
      </div>
      <div className='admineditnamecon'>
            <div className='admineditname'>
            <p>Content</p>
            <TextEditor content={content} setContent={setContent}/>
            </div>
        </div>
    </>
  )
}
