import Head from 'next/head';
import dynamic from "next/dynamic";
import { useState } from 'react';
import Swal from 'sweetalert2';
import Link from 'next/link';
const SunEditor=dynamic(import("@/components/SunEditor"), { ssr: false });

export default function Sun() {
  const [content, setContent] = useState('');

  const handleClick=()=>{
    Swal.fire(
      'Result Text',
      content,
      'success'
    )
  }


  return (
    <>
      <Head>
        <title>Sun Editor</title>
        <meta name="description" content="Generated by Steven Joseph" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Sun Editor</h1>
        <Link href='/'>Back Home</Link>
      </div>
      <div className='admineditnamecon'>
            <div className='admineditname'>
            <p>Contents</p>
            <SunEditor content={content} setContent={setContent}/>
            </div>
        </div>
        <div>
            <button onClick={()=>handleClick()}>Show Text</button>
        </div>
    </>
  )
}
